{
 "title": "Temporal Cloud External Metrics (OpenMetrics)",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "temporal_namespace",
    "query": {
     "query": "label_values(temporal_cloud_v1_frontend_service_request_count,temporal_namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Open Workflows",
   "type": "stat",
   "description": "The last known number of open workflows in the namespace",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(temporal_cloud_v1_namespace_open_workflows{temporal_namespace=~\"$temporal_namespace\"}) by (temporal_namespace)",
     "legendFormat": "{{temporal_namespace}}"
    }
   ]
  },
  {
   "title": "Failed Workflows",
   "type": "table",
   "description": "A list of failed workflows in the namespace",
   "gridPos": { "h": 9, "w": 19, "x": 5, "y": 1 },
   "targets": [
    {
     "expr": "sum(sum_over_time(temporal_cloud_v1_workflow_failed_count{temporal_namespace=~\"$temporal_namespace\"}[$__range])/($__range_s / 60) * $__range_s) by (temporal_workflow_type, temporal_namespace, temporal_task_queue)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task Backlog",
   "type": "timeseries",
   "description": "The approximate number of tasks in the backlog for each task queue",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(temporal_cloud_v1_approximate_backlog_count{temporal_namespace=~\"$temporal_namespace\"}) by (temporal_task_queue)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sync Match Rate",
   "type": "timeseries",
   "description": "The proportion of Tasks that are delivered directly to Stickied Cached Workflows on Workers, compared to the total number of delivered Tasks.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(temporal_cloud_v1_poll_success_sync_count{temporal_namespace=~\"$temporal_namespace\"}) by (temporal_task_queue) /\nsum(temporal_cloud_v1_poll_success_count{temporal_namespace=~\"$temporal_namespace\"}) by(temporal_task_queue)",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Workflows",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Success",
     "type": "timeseries",
     "description": "The number of successful workflow completions per second",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "sum(temporal_cloud_v1_workflow_success_count{temporal_namespace=~\"$temporal_namespace\"}) by (temporal_namespace)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Success / Workflow Type",
     "type": "timeseries",
     "description": "The number of successful workflow completions per second",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 20 },
     "targets": [
      {
       "expr": "sum(temporal_cloud_v1_workflow_success_count{temporal_namespace=~\"$temporal_namespace\"}) by (temporal_workflow_type)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Success / Task Queue",
     "type": "timeseries",
     "description": "The number of successful workflow completions per second",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 20 },
     "targets": [
      {
       "expr": "sum(temporal_cloud_v1_workflow_success_count{temporal_namespace=~\"$temporal_namespace\"}) by (temporal_task_queue)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Failed",
     "type": "timeseries",
     "description": "The number of failed workflow completions per second",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 93 },
     "targets": [
      {
       "expr": "sum(temporal_cloud_v1_workflow_failed_count{temporal_namespace=~\"$temporal_namespace\"}) by (temporal_namespace)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Failed / Workflow Type",
     "type": "timeseries",
     "description": "The number of failed workflow completions per second",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 93 },
     "targets": [
      {
       "expr": "sum(temporal_cloud_v1_workflow_failed_count{temporal_namespace=~\"$temporal_namespace\"}) by (temporal_workflow_type)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Failed / Task Queue",
     "type": "timeseries",
     "description": "The number of failed workflow completions per second",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 93 },
     "targets": [
      {
       "expr": "sum(temporal_cloud_v1_workflow_failed_count{temporal_namespace=~\"$temporal_namespace\"}) by (temporal_task_queue)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Continued as New",
     "type": "timeseries",
     "description": "The number of continued-as-new workflow completions per second",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 102 },
     "targets": [
      {
       "expr": "sum(temporal_cloud_v1_workflow_continued_as_new_count{temporal_namespace=~\"$temporal_namespace\"}) by (temporal_namespace)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Continued as New / Workflow Type",
     "type": "timeseries",
     "description": "The number of continued-as-new workflow completions per second",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 102 },
     "targets": [
      {
       "expr": "sum(temporal_cloud_v1_workflow_continued_as_new_count{temporal_namespace=~\"$temporal_namespace\"}) by (temporal_workflow_type)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Continued as New / Task Queue",
     "type": "timeseries",
     "description": "The number of continued-as-new workflow completions per second",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 102 },
     "targets": [
      {
       "expr": "sum(temporal_cloud_v1_workflow_continued_as_new_count{temporal_namespace=~\"$temporal_namespace\"}) by (temporal_task_queue)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Cancels",
     "type": "timeseries",
     "description": "The number of canceled workflow completions per second",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 111 },
     "targets": [
      {
       "expr": "sum(temporal_cloud_v1_workflow_cancel_count{temporal_namespace=~\"$temporal_namespace\"}) by (temporal_namespace)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Cancels / Workflow Type",
     "type": "timeseries",
     "description": "The number of canceled workflow completions per second",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 111 },
     "targets": [
      {
       "expr": "sum(temporal_cloud_v1_workflow_cancel_count{temporal_namespace=~\"$temporal_namespace\"}) by (temporal_workflow_type)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Cancels / Task Queue",
     "type": "timeseries",
     "description": "The number of canceled workflow completions per second",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 111 },
     "targets": [
      {
       "expr": "sum(temporal_cloud_v1_workflow_cancel_count{temporal_namespace=~\"$temporal_namespace\"}) by (temporal_task_queue)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Timeouts",
     "type": "timeseries",
     "description": "The number of timed-out workflow completions per second",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 120 },
     "targets": [
      {
       "expr": "sum(temporal_cloud_v1_workflow_timeout_count{temporal_namespace=~\"$temporal_namespace\"}) by (temporal_namespace)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Timeouts / Workflow Type",
     "type": "timeseries",
     "description": "The number of timed-out workflow completions per second",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 120 },
     "targets": [
      {
       "expr": "sum(temporal_cloud_v1_workflow_timeout_count{temporal_namespace=~\"$temporal_namespace\"}) by (temporal_workflow_type)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Timeouts / Task Queue",
     "type": "timeseries",
     "description": "The number of timed-out workflow completions per second",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 120 },
     "targets": [
      {
       "expr": "sum(temporal_cloud_v1_workflow_timeout_count{temporal_namespace=~\"$temporal_namespace\"}) by (temporal_task_queue)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Task Queue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "No Poller Tasks",
     "type": "timeseries",
     "description": "The per-second rate of tasks added to a task queue with no pollers",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(temporal_cloud_v1_no_poller_tasks_count{temporal_namespace=~\"$temporal_namespace\"}) by (temporal_task_queue)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Poll Success",
     "type": "timeseries",
     "description": "The number of successfully matched tasks per second",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
     "targets": [
      {
       "expr": "sum(temporal_cloud_v1_poll_success_count{temporal_namespace=~\"$temporal_namespace\"}) by (temporal_task_queue)",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Poll Timeout",
     "type": "timeseries",
     "description": "The per second rate of occurrences where no tasks are available for a poller before timing out",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 94 },
     "targets": [
      {
       "expr": "sum(temporal_cloud_v1_poll_timeout_count{temporal_namespace=~\"$temporal_namespace\"}) by (temporal_task_queue)",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Poll Success Sync",
     "type": "timeseries",
     "description": "The number of successfully sync matched tasks per second",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 94 },
     "targets": [
      {
       "expr": "sum(temporal_cloud_v1_poll_success_sync_count{temporal_namespace=~\"$temporal_namespace\"}) by (temporal_task_queue)",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Poll Success Async",
     "type": "timeseries",
     "description": "The number of successfully async matched tasks per second\n\nAn async match is when a Task cannot be matched to the Sticky Queue for a Worker. ",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 103 },
     "targets": [
      {
       "expr": "sum(temporal_cloud_v1_poll_success_count{temporal_namespace=~\"$temporal_namespace\"}) by (temporal_task_queue) - sum(temporal_cloud_v1_poll_success_sync_count{temporal_namespace=~\"$temporal_namespace\"}) by (temporal_task_queue)",
       "legendFormat": "{{operation}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Usage & Quotas",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Actions",
     "type": "timeseries",
     "description": "The number of actions taken per second vs the current limit for the namespace",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "sum(temporal_cloud_v1_total_action_count{temporal_namespace=~\"$temporal_namespace\"}) by (temporal_namespace)",
       "legendFormat": "APS (actions per second)"
      },
      {
       "expr": "temporal_cloud_v1_action_limit{temporal_namespace=~\"$temporal_namespace\"} or vector(400)",
       "legendFormat": "limit"
      }
     ]
    },
    {
     "title": "30 Days Actions",
     "type": "stat",
     "description": "Approximate number of actions over the last 30 days",
     "gridPos": { "h": 9, "w": 4, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(sum_over_time(temporal_cloud_v1_total_action_count{temporal_namespace=~\"$temporal_namespace\"}[30d])/(30 * 24 * 60) * 30 * 24 * 60 * 60)",
       "legendFormat": "{{temporal_namespace}}"
      }
     ]
    },
    {
     "title": "7 Days Actions",
     "type": "stat",
     "description": "Approximate number of actions over the last 7 days",
     "gridPos": { "h": 9, "w": 4, "x": 16, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(sum_over_time(temporal_cloud_v1_total_action_count{temporal_namespace=~\"$temporal_namespace\"}[7d])/(7 * 24 * 60) * 7 * 24 * 60 * 60)",
       "legendFormat": "{{temporal_namespace}}"
      }
     ]
    },
    {
     "title": "1 Day Actions",
     "type": "stat",
     "description": "Approximate number of actions over the last day",
     "gridPos": { "h": 9, "w": 4, "x": 20, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(sum_over_time(temporal_cloud_v1_total_action_count{temporal_namespace=~\"$temporal_namespace\"}[1d])/(1 * 24 * 60) * 1 * 24 * 60 * 60)",
       "legendFormat": "{{temporal_namespace}}"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "timeseries",
     "description": "The number of requests per second against the current limit for the namespace",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 95 },
     "targets": [
      {
       "expr": "sum(temporal_cloud_v1_frontend_service_request_count{temporal_namespace=~\"$temporal_namespace\"}) by (temporal_namespace)",
       "legendFormat": "RPS (requests per second)"
      },
      {
       "expr": "temporal_cloud_v1_frontend_rps_limit{temporal_namespace=~\"$temporal_namespace\"} or vector(1600)",
       "legendFormat": "limit"
      }
     ]
    },
    {
     "title": "Operations",
     "type": "timeseries",
     "description": "The number of operations and throttled operations per second against the current limit",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 95 },
     "targets": [
      {
       "expr": "sum(temporal_cloud_v1_operations_count{temporal_namespace=~\"$temporal_namespace\"}) by (temporal_namespace)",
       "legendFormat": "OPS (operations per second)"
      },
      { "expr": "vector(3200)", "legendFormat": "limit" },
      {
       "expr": "sum(temporal_cloud_v1_operations_throttled_count{temporal_namespace=~\"$temporal_namespace\"}) by (temporal_namespace)",
       "legendFormat": "throttled"
      }
     ]
    }
   ]
  },
  {
   "title": "Schedules",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Successful Schedule Actions",
     "type": "timeseries",
     "description": "Number of successfully scheduled workflow executions per second",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "sum(temporal_cloud_v1_schedule_action_success_count{temporal_namespace=~\"$temporal_namespace\"}) by (temporal_namespace)",
       "legendFormat": "{{temporal_namespace}}"
      }
     ]
    },
    {
     "title": "Schedule Buffer Overruns",
     "type": "timeseries",
     "description": "Number of occurences the average schedule run length is greater than average schedule interval while a buffer_all overlap policy is configured.",
     "gridPos": { "h": 9, "w": 4, "x": 12, "y": 23 },
     "targets": [
      {
       "expr": "sum(temporal_cloud_v1_schedule_buffer_overruns_count{temporal_namespace=~\"$temporal_namespace\"}) by (temporal_namespace)",
       "legendFormat": "{{temporal_namespace}}"
      }
     ]
    },
    {
     "title": "Schedule Missed Catchup Windows",
     "type": "timeseries",
     "description": "The per-second rate of skipped Scheduled executions when Workflows were delayed longer than the catchup window.",
     "gridPos": { "h": 9, "w": 4, "x": 16, "y": 23 },
     "targets": [
      {
       "expr": "sum(temporal_cloud_v1_schedule_missed_catchup_window_count{temporal_namespace=~\"$temporal_namespace\"}) by (temporal_namespace)",
       "legendFormat": "{{temporal_namespace}}"
      }
     ]
    },
    {
     "title": "Schedules Rate Limited",
     "type": "timeseries",
     "description": "The per-second rate of number of rate-limited scheduled workflows",
     "gridPos": { "h": 9, "w": 4, "x": 20, "y": 23 },
     "targets": [
      {
       "expr": "sum(temporal_cloud_v1_schedule_rate_limited_count{temporal_namespace=~\"$temporal_namespace\"}) by (temporal_namespace)",
       "legendFormat": "{{temporal_namespace}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests",
     "type": "timeseries",
     "description": "The number of requests per second",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "sum(temporal_cloud_v1_frontend_service_request_count{temporal_namespace=~\"$temporal_namespace\"}) by (temporal_namespace)",
       "legendFormat": "RPS (requests per second)"
      },
      {
       "expr": "temporal_cloud_v1_frontend_rps_limit{temporal_namespace=~\"$temporal_namespace\"} or vector(1600)",
       "legendFormat": "limit"
      }
     ]
    },
    {
     "title": "Frontend Service Requests / Operation",
     "type": "timeseries",
     "description": "The number of requests per second by operation",
     "gridPos": { "h": 9, "w": 13, "x": 11, "y": 24 },
     "targets": [
      {
       "expr": "sum(temporal_cloud_v1_frontend_service_request_count{temporal_namespace=~\"$temporal_namespace\"}) by (temporal_namespace,operation)",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Frontend Service Errors",
     "type": "timeseries",
     "description": "The number of request errors per second",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 51 },
     "targets": [
      {
       "expr": "sum(temporal_cloud_v1_frontend_service_error_count{temporal_namespace=~\"$temporal_namespace\"}) by (temporal_namespace)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Frontend Service Errors / Operation",
     "type": "timeseries",
     "description": "The number of request errors per second by operation",
     "gridPos": { "h": 9, "w": 6, "x": 11, "y": 51 },
     "targets": [
      {
       "expr": "sum(temporal_cloud_v1_frontend_service_error_count{temporal_namespace=~\"$temporal_namespace\"}) by (temporal_namespace,operation)",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Resource Exhausted Errors",
     "type": "timeseries",
     "description": "The number of resource exhausted errors per second",
     "gridPos": { "h": 9, "w": 7, "x": 17, "y": 51 },
     "targets": [
      {
       "expr": "sum(temporal_cloud_v1_resource_exhausted_error_count{temporal_namespace=~\"$temporal_namespace\"}) by (temporal_namespace, resource_exhausted_cause)",
       "legendFormat": "{{temporal_namespace}}-{{resource_exhausted_cause}}"
      }
     ]
    },
    {
     "title": "Replication Lag",
     "type": "timeseries",
     "description": "Replication lag across regions for a high-availability namespace",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "temporal_cloud_v1_replication_lag_p50{temporal_namespace=~\"$temporal_namespace\"}",
       "legendFormat": "50th Percentile"
      },
      {
       "expr": "temporal_cloud_v1_replication_lag_p95{temporal_namespace=~\"$temporal_namespace\"}",
       "legendFormat": "95th Percentile"
      },
      {
       "expr": "temporal_cloud_v1_replication_lag_p99{temporal_namespace=~\"$temporal_namespace\"}",
       "legendFormat": "99th Percentile"
      }
     ]
    }
   ]
  },
  {
   "title": "Service Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "StartWorkflowExecution Latency",
     "type": "timeseries",
     "description": "The percentile latencies for StartWorkflowExecution operations",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "temporal_cloud_v1_service_latency_p50{temporal_namespace=~\"$temporal_namespace\", operation=\"StartWorkflowExecution\"}",
       "legendFormat": "50th Percentile"
      },
      {
       "expr": "temporal_cloud_v1_service_latency_p95{temporal_namespace=~\"$temporal_namespace\", operation=\"StartWorkflowExecution\"}",
       "legendFormat": "95th Percentile"
      },
      {
       "expr": "temporal_cloud_v1_service_latency_p99{temporal_namespace=~\"$temporal_namespace\", operation=\"StartWorkflowExecution\"}",
       "legendFormat": "99th Percentile"
      }
     ]
    },
    {
     "title": "SignalWorkflowExecution Latency",
     "type": "timeseries",
     "description": "The percentile latencies for SignalWorkflowExecution operations",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "temporal_cloud_v1_service_latency_p50{temporal_namespace=~\"$temporal_namespace\", operation=\"SignalWorkflowExecution\"}",
       "legendFormat": "50th Percentile"
      },
      {
       "expr": "temporal_cloud_v1_service_latency_p95{temporal_namespace=~\"$temporal_namespace\", operation=\"SignalWorkflowExecution\"}",
       "legendFormat": "95th Percentile"
      },
      {
       "expr": "temporal_cloud_v1_service_latency_p99{temporal_namespace=~\"$temporal_namespace\", operation=\"SignalWorkflowExecution\"}",
       "legendFormat": "99th Percentile"
      }
     ]
    },
    {
     "title": "SignalWithStartWorkflowExecution Latency",
     "type": "timeseries",
     "description": "The percentile latencies for SignalWithStartWorkflowExecution operations",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "temporal_cloud_v1_service_latency_p50{temporal_namespace=~\"$temporal_namespace\", operation=\"SignalWithStartWorkflowExecution\"}",
       "legendFormat": "50th Percentile"
      },
      {
       "expr": "temporal_cloud_v1_service_latency_p95{temporal_namespace=~\"$temporal_namespace\", operation=\"SignalWithStartWorkflowExecution\"}",
       "legendFormat": "95th Percentile"
      },
      {
       "expr": "temporal_cloud_v1_service_latency_p99{temporal_namespace=~\"$temporal_namespace\", operation=\"SignalWithStartWorkflowExecution\"}",
       "legendFormat": "99th Percentile"
      }
     ]
    }
   ]
  },
  {
   "title": "Self Hosted -> Cloud Migration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "State Transitions",
     "type": "timeseries",
     "description": "The number of state transitions per second",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "sum(temporal_cloud_v1_state_transition_count{temporal_namespace=~\"$temporal_namespace\"}) by (temporal_namespace)",
       "legendFormat": "{{temporal_namespace}}"
      }
     ]
    },
    {
     "title": "30 Day State Transitions",
     "type": "stat",
     "description": "The number of state transitions over the past 30 days",
     "gridPos": { "h": 9, "w": 4, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(sum_over_time(temporal_cloud_v1_state_transition_count{temporal_namespace=~\"$temporal_namespace\"}[30d])/(30 * 24 * 60) * 30 * 24 * 60 * 60)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "7 Day State Transitions",
     "type": "stat",
     "description": "The number of state transitions over the past 7 days",
     "gridPos": { "h": 9, "w": 4, "x": 16, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(sum_over_time(temporal_cloud_v1_state_transition_count{temporal_namespace=~\"$temporal_namespace\"}[7d])/(7 * 24 * 60) * 7 * 24 * 60 * 60)",
       "legendFormat": "{{temporal_namespace}}"
      }
     ]
    },
    {
     "title": "1 Day State Transitions",
     "type": "stat",
     "description": "The number of state transitions over the past day",
     "gridPos": { "h": 9, "w": 4, "x": 20, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(sum_over_time(temporal_cloud_v1_state_transition_count{temporal_namespace=~\"$temporal_namespace\"}[1d])/(1 * 24 * 60) * 1 * 24 * 60 * 60)",
       "legendFormat": "{{temporal_namespace}}"
      }
     ]
    },
    {
     "title": "Actions / State Transitions",
     "type": "timeseries",
     "description": "The approximate number of actions per state transition",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "sum(temporal_cloud_v1_total_action_count{temporal_namespace=~\"$temporal_namespace\"}) by (temporal_namespace) / sum(temporal_cloud_v1_state_transition_count{temporal_namespace=~\"${temporal_namespace}\"}) by (temporal_namespace)",
       "legendFormat": "ratio"
      }
     ]
    }
   ]
  }
 ]
}