{
 "title": "Temporal Cloud External Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "temporal_namespace",
    "query": {
     "query": "label_values(temporal_namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Actions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Actions",
   "type": "timeseries",
   "description": "Approximate count of Temporal Cloud Actions per-second. Use `namespace_mode` to filter for active/standby actions for multi-region namespaces. More information about [billable actions](https://docs.temporal.io/cloud/pricing#action).",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "APS" } },
   "targets": [
    {
     "expr": "sum(rate(temporal_cloud_v0_total_action_count{temporal_namespace=~\"$temporal_namespace\", namespace_mode=\"active\"}[$__rate_interval])) by (temporal_namespace)",
     "legendFormat": "{{temporal_namespace}}"
    }
   ]
  },
  {
   "title": "30 Days Actions",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(temporal_cloud_v0_total_action_count{temporal_namespace=~\"$temporal_namespace\", namespace_mode=\"active\"}[30d])) by (temporal_namespace)",
     "legendFormat": "{{temporal_namespace}}"
    }
   ]
  },
  {
   "title": "7 Days Actions",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(temporal_cloud_v0_total_action_count{temporal_namespace=~\"$temporal_namespace\", namespace_mode=\"active\"}[7d])) by (temporal_namespace)",
     "legendFormat": "{{temporal_namespace}}"
    }
   ]
  },
  {
   "title": "1 Day Actions",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(temporal_cloud_v0_total_action_count{temporal_namespace=~\"$temporal_namespace\", namespace_mode=\"active\"}[1d])) by (temporal_namespace)",
     "legendFormat": "{{temporal_namespace}}"
    }
   ]
  },
  { "title": "Workflows Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Workflow Success",
   "type": "timeseries",
   "description": "Workflows that successfully completed.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(rate(temporal_cloud_v0_workflow_success_count{temporal_namespace=~\"$temporal_namespace\"}[$__rate_interval])) by (temporal_namespace)",
     "legendFormat": "{{temporal_namespace}}"
    }
   ]
  },
  {
   "title": "Workflow Timeouts",
   "type": "timeseries",
   "description": "Workflows that timed out before completing execution.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "sum(rate(temporal_cloud_v0_workflow_timeout_count{temporal_namespace=~\"$temporal_namespace\"}[$__rate_interval])) by (temporal_namespace)",
     "legendFormat": "{{temporal_namespace}}"
    }
   ]
  },
  {
   "title": "Workflow Failed",
   "type": "timeseries",
   "description": "Workflows that failed before completion.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(rate(temporal_cloud_v0_workflow_failed_count{temporal_namespace=~\"$temporal_namespace\"}[$__rate_interval])) by (temporal_namespace)",
     "legendFormat": "{{temporal_namespace}}"
    }
   ]
  },
  {
   "title": "Workflow Continued as New",
   "type": "timeseries",
   "description": "Workflow Executions that were Continued-As-New from a past execution.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "sum(rate(temporal_cloud_v0_workflow_continued_as_new_count{temporal_namespace=~\"$temporal_namespace\"}[$__rate_interval])) by (temporal_namespace)",
     "legendFormat": "{{temporal_namespace}}"
    }
   ]
  },
  {
   "title": "Workflow Terminations",
   "type": "timeseries",
   "description": "Workflows terminated before completing execution.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum(rate(temporal_cloud_v0_workflow_terminate_count{temporal_namespace=~\"$temporal_namespace\"}[$__rate_interval])) by (temporal_namespace)",
     "legendFormat": "{{temporal_namespace}}"
    }
   ]
  },
  {
   "title": "Workflow Cancellations",
   "type": "timeseries",
   "description": "Workflows canceled before completing execution.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "sum(rate(temporal_cloud_v0_workflow_cancel_count{temporal_namespace=~\"$temporal_namespace\"}[$__rate_interval])) by (temporal_namespace)",
     "legendFormat": "{{temporal_namespace}}"
    }
   ]
  },
  { "title": "Schedules", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Successful Schedule Actions",
   "type": "timeseries",
   "description": "Successful execution of a Scheduled Workflow.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "sum(rate(temporal_cloud_v0_schedule_action_success_count{temporal_namespace=~\"$temporal_namespace\"}[$__rate_interval])) by (temporal_namespace)",
     "legendFormat": "{{temporal_namespace}}"
    }
   ]
  },
  {
   "title": "Schedule Buffer Overruns",
   "type": "timeseries",
   "description": "When average schedule run length is greater than average schedule interval while a buffer_all overlap policy is configured.",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "sum(rate(temporal_cloud_v0_schedule_buffer_overruns_count{temporal_namespace=~\"$temporal_namespace\"}[$__rate_interval])) by (temporal_namespace)",
     "legendFormat": "{{temporal_namespace}}"
    }
   ]
  },
  {
   "title": "Schedule Missed Catchup Windows",
   "type": "timeseries",
   "description": "Skipped Scheduled executions when Workflows were delayed longer than the catchup window.",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 39 },
   "targets": [
    {
     "expr": "sum(rate(temporal_cloud_v0_schedule_missed_catchup_window_count{temporal_namespace=~\"$temporal_namespace\"}[$__rate_interval])) by (temporal_namespace)",
     "legendFormat": "{{temporal_namespace}}"
    }
   ]
  },
  {
   "title": "Schedules Rate Limited",
   "type": "timeseries",
   "description": "Workflows that were delayed due to exceeding a rate limit.",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 39 },
   "targets": [
    {
     "expr": "sum(rate(temporal_cloud_v0_schedule_rate_limited_count{temporal_namespace=~\"$temporal_namespace\"}[$__rate_interval])) by (temporal_namespace)",
     "legendFormat": "{{temporal_namespace}}"
    }
   ]
  },
  { "title": "Workers and Tasks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Sync Match Rate",
   "type": "timeseries",
   "description": "The Sync Match Rate measures the rate of Tasks that can be delivered to Workers without having to be persisted (Workers are up and available to pick them up) to the rate of all delivered Tasks. [more info](https://docs.temporal.io/production-deployment/cloud/worker-health#sync-match-rate)\n\nShould always be near 100%.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(temporal_namespace,task_type) (\n   rate(\n     temporal_cloud_v0_poll_success_sync_count{temporal_namespace=~\"$temporal_namespace\"}[$__rate_interval]\n   )\n  )\n/\nsum by(temporal_namespace,task_type) (\n   rate(\n     temporal_cloud_v0_poll_success_count{temporal_namespace=~\"$temporal_namespace\"}[$__rate_interval]\n    )\n  )",
     "legendFormat": "{{temporal_namespace}} - {{task_type}}"
    }
   ]
  },
  {
   "title": "Worker Poll Success",
   "type": "timeseries",
   "description": "Tasks that are successfully matched to a poller.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "sum(rate(temporal_cloud_v0_poll_success_count{temporal_namespace=~\"$temporal_namespace\"}[$__rate_interval])) by (temporal_namespace, task_type)",
     "legendFormat": "{{temporal_namespace}} - {{task_type}}"
    }
   ]
  },
  {
   "title": "Worker Poll Success Sync",
   "type": "timeseries",
   "description": "Tasks that are successfully sync matched to a poller.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "sum(rate(temporal_cloud_v0_poll_success_sync_count{temporal_namespace=~\"$temporal_namespace\"}[$__rate_interval])) by (temporal_namespace,task_type)",
     "legendFormat": "{{temporal_namespace}} - {{task_type}}"
    }
   ]
  },
  {
   "title": "Worker Poll Success Async",
   "type": "timeseries",
   "description": "Tasks that are successfully async matched to a poller.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "expr": "sum(rate(temporal_cloud_v0_poll_success_count{temporal_namespace=~\"$temporal_namespace\"}[$__rate_interval])) by (temporal_namespace, task_type) - sum(rate(temporal_cloud_v0_poll_success_sync_count{temporal_namespace=~\"$temporal_namespace\"}[$__rate_interval])) by (temporal_namespace, task_type)",
     "legendFormat": "{{temporal_namespace}} - {{task_type}}"
    }
   ]
  },
  {
   "title": "Poll Success Rate",
   "type": "timeseries",
   "description": "Successful task matching to poller\n/\nAll polling requests (including timeouts)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n    (\n        sum by(temporal_namespace, task_type) (\n          rate(\n            temporal_cloud_v0_poll_success_count{temporal_namespace=~\"$temporal_namespace\"}[$__rate_interval]\n          )\n        )\n      +\n        sum by(temporal_namespace, task_type) (\n          rate(\n            temporal_cloud_v0_poll_success_sync_count{temporal_namespace=~\"$temporal_namespace\"}[$__rate_interval]\n          )\n        )\n    )\n  /\n    (\n        (\n            sum by(temporal_namespace, task_type) (\n              rate(\n                temporal_cloud_v0_poll_success_count{temporal_namespace=~\"$temporal_namespace\"}[$__rate_interval]\n              )\n            )\n          +\n            sum by(temporal_namespace, task_type) (\n              rate(\n                temporal_cloud_v0_poll_success_sync_count{temporal_namespace=~\"$temporal_namespace\"}[$__rate_interval]\n              )\n            )\n        )\n      +\n        sum by(temporal_namespace, task_type) (\n          rate(\n            temporal_cloud_v0_poll_timeout_count{temporal_namespace=~\"$temporal_namespace\"}[$__rate_interval]\n          )\n        )\n    )\n)",
     "legendFormat": "{{temporal_namespace}} - {{task_type}}"
    }
   ]
  },
  {
   "title": "Worker Poll Timeout",
   "type": "timeseries",
   "description": "When no tasks are available for a poller before timing out. If this is high, you may have too many pollers.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 67 },
   "targets": [
    {
     "expr": "sum(rate(temporal_cloud_v0_poll_timeout_count{temporal_namespace=~\"$temporal_namespace\"}[$__rate_interval])) by (temporal_namespace, task_type)",
     "legendFormat": "{{temporal_namespace}} - {{task_type}}"
    }
   ]
  },
  { "title": "Temporal Cloud gRPC Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Frontend Service Requests",
   "type": "timeseries",
   "description": "A count of gRPC requests received aggregated by operation.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 77 },
   "targets": [
    {
     "expr": "sum(rate(temporal_cloud_v0_frontend_service_request_count{temporal_namespace=~\"$temporal_namespace\"}[$__rate_interval])) by (temporal_namespace,operation)",
     "legendFormat": "{{temporal_namespace}} - {{operation}}"
    }
   ]
  },
  {
   "title": "Frontend Service Errors",
   "type": "timeseries",
   "description": "Count of gRPC errors returned aggregated by operation, including resource exhausted errors.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 77 },
   "targets": [
    {
     "expr": "sum(rate(temporal_cloud_v0_frontend_service_error_count{temporal_namespace=~\"$temporal_namespace\"}[$__rate_interval])) by (temporal_namespace,operation)",
     "legendFormat": "{{temporal_namespace}} - {{operation}}"
    },
    {
     "expr": "sum(rate(temporal_cloud_v0_resource_exhausted_error_count{temporal_namespace=~\"$temporal_namespace\"}[$__rate_interval])) by (temporal_namespace,operation,resource_exhausted_cause)",
     "legendFormat": "Rate Limited - {{ resource_exhausted_cause }} / {{temporal_namespace}}"
    }
   ]
  },
  { "title": "Temporal Service Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 } },
  {
   "title": "StartWorkflowExecution Latency",
   "type": "timeseries",
   "description": "Should generally be under 200ms",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(temporal_cloud_v0_service_latency_bucket{temporal_namespace=~\"$temporal_namespace\", operation=\"StartWorkflowExecution\"}[$__rate_interval])) by (temporal_namespace, operation, le))",
     "legendFormat": "{{ temporal_namespace }}  - 50th Percentile"
    }
   ]
  },
  {
   "title": "SignalWorkflowExecution Latency",
   "type": "timeseries",
   "description": "Should generally be under 200ms",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(temporal_cloud_v0_service_latency_bucket{temporal_namespace=~\"$temporal_namespace\", operation=\"SignalWorkflowExecution\"}[$__rate_interval])) by (temporal_namespace, operation, le))",
     "legendFormat": "{{ temporal_namespace }}  - 50th Percentile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(temporal_cloud_v0_service_latency_bucket{temporal_namespace=~\"$temporal_namespace\", operation=\"SignalWorkflowExecution\"}[$__rate_interval])) by (temporal_namespace, operation, le))",
     "legendFormat": "{{ temporal_namespace }}  - 99th Percentile"
    }
   ]
  },
  {
   "title": "SignalWithStartWorkflowExecution Latency",
   "type": "timeseries",
   "description": "Should generally be under 200ms",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(temporal_cloud_v0_service_latency_bucket{temporal_namespace=~\"$temporal_namespace\", operation=\"SignalWithStartWorkflowExecution\"}[$__rate_interval])) by (temporal_namespace, operation, le))",
     "legendFormat": "{{ temporal_namespace }}  - 50th Percentile"
    }
   ]
  },
  { "title": "Multi-region Namespaces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 } },
  {
   "title": "Replication Lag",
   "type": "timeseries",
   "description": "The transmission delay of Workflow updates and history events from the primary to the replica. [more info](https://docs.temporal.io/cloud/high-availability/monitor#metrics)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(temporal_cloud_v0_replication_lag_sum{temporal_namespace=~\"$temporal_namespace\"}[$__rate_interval])) by (temporal_namespace)\n/\nsum(rate(temporal_cloud_v0_replication_lag_count{temporal_namespace=~\"$temporal_namespace\"}[$__rate_interval])) by (temporal_namespace)",
     "legendFormat": "{{ temporal_namespace }} - p50"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(temporal_cloud_v0_replication_lag_bucket{temporal_namespace=~\"$temporal_namespace\"}[$__rate_interval])) by (temporal_namespace, le))",
     "legendFormat": "{{ temporal_namespace }} - p99"
    }
   ]
  },
  {
   "title": "Actions",
   "type": "timeseries",
   "description": "[Billable actions](https://docs.temporal.io/cloud/pricing#action) split across active/standby namespaces for multi region namespaces.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 98 },
   "targets": [
    {
     "expr": "sum(rate(temporal_cloud_v0_total_action_count{temporal_namespace=~\"$temporal_namespace\"}[$__rate_interval])) by (temporal_namespace, namespace_mode)",
     "legendFormat": "{{temporal_namespace}} - {{ namespace_mode }}"
    }
   ]
  },
  { "title": "State Transitions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 107 } },
  {
   "title": "State Transitions",
   "type": "timeseries",
   "description": "Count of state transitions for each Namespace.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 108 },
   "targets": [
    {
     "expr": "sum(rate(temporal_cloud_v0_state_transition_count{temporal_namespace=~\"$temporal_namespace\"}[$__rate_interval])) by (temporal_namespace)",
     "legendFormat": "{{temporal_namespace}}"
    }
   ]
  },
  {
   "title": "30 Day State Transitions",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(temporal_cloud_v0_state_transition_count{temporal_namespace=~\"$temporal_namespace\"}[30d])) by (temporal_namespace)",
     "legendFormat": "{{temporal_namespace}}"
    }
   ]
  },
  {
   "title": "7 Day State Transitions",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(temporal_cloud_v0_state_transition_count{temporal_namespace=~\"$temporal_namespace\"}[7d])) by (temporal_namespace)",
     "legendFormat": "{{temporal_namespace}}"
    }
   ]
  },
  {
   "title": "1 Day State Transitions",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(temporal_cloud_v0_state_transition_count{temporal_namespace=~\"$temporal_namespace\"}[1d])) by (temporal_namespace)",
     "legendFormat": "{{temporal_namespace}}"
    }
   ]
  }
 ]
}