version: "3.5"
services:
  temporal:
    environment:
      - METRICS_EXPORTER=prometheus
      - PROMETHEUS_ENDPOINT=0.0.0.0:8003
    ports:
      - 8003:8003
  postgresql:
    ports:
      - 5432:5432
