receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
#
#  prometheus:
#    config:
#      scrape_configs:
#        - job_name: 'java-worker-and-client'
#          scrape_interval: 5s
#          static_configs:
#            - targets: [ 'java-worker:8071' ]
#            - targets: [ 'localhost:8079' ]
processors:
  batch:
    send_batch_max_size: 1000
    timeout: 30s
    send_batch_size: 800


exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"

  debug:


service:
  pipelines:
    metrics:
      receivers: [otlp ]
      processors: [ batch ]
      exporters: [ debug, prometheus ]
    traces:
      receivers: [otlp ]
      processors: [ batch ]
      exporters: [ debug ]

