receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 10s
          static_configs:
            - targets: [ 'java-worker:80711' ]
processors:
  batch:
    send_batch_max_size: 1000
    timeout: 30s
    send_batch_size: 800


exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"

service:
  extensions: [ ]
  pipelines:
    metrics:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ prometheus ]