version: "3.5"
services:
  grafana:
      image: grafana/grafana:9.1.4
      ports:
        - 3000:3000
      restart: unless-stopped
      environment:
        - GF_AUTH_DISABLE_LOGIN_FORM=true
        - GF_AUTH_ANONYMOUS_ENABLED=true
        - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      volumes:
        - ./docker_data/grafana_data:/var/lib/grafana
      depends_on:
        - prometheus        

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.37.0
    ports:
      - 9090:9090
    volumes:
      - ./docker_data/prometheus:/prometheus 
      - type: bind
        source: ./deployment/prometheus/config.yml
        target: /etc/prometheus/prometheus.yml