#!/bin/sh


source 2-stop-workers.sh

export MAX_TASKQUEUE_ACTIVITIES_PER_SECOND=10000
export CONCURRENT_ACTIVITY_EXECUTION_SIZE=600
export CONCURRENT_WORKFLOW_EXECUTION_SIZE=600
export MAX_WORKFLOW_THREAD_COUNT=10000
export CACHE_SIZE=600
export DISABLE_EAGER_DISPATCH=true


export SLEEP_ACTIVITY_IN_MS=1000

export PQL_PORT=8071
docker run -d -p $PQL_PORT:$PQL_PORT -e PQL_PORT=$PQL_PORT -e MAX_TASKQUEUE_ACTIVITIES_PER_SECOND=$MAX_TASKQUEUE_ACTIVITIES_PER_SECOND \
-e CONCURRENT_ACTIVITY_EXECUTION_SIZE=$CONCURRENT_ACTIVITY_EXECUTION_SIZE  \
-e CONCURRENT_WORKFLOW_EXECUTION_SIZE=$CONCURRENT_WORKFLOW_EXECUTION_SIZE  \
-e MAX_WORKFLOW_THREAD_COUNT=$MAX_WORKFLOW_THREAD_COUNT  \
-e DISABLE_EAGER_DISPATCH=DISABLE_EAGER_DISPATCH  \
-e CACHE_SIZE=$CACHE_SIZE  \
-e SLEEP_ACTIVITY_IN_MS=$SLEEP_ACTIVITY_IN_MS my-metric-worker-java

export PQL_PORT=8072
docker run -d -p $PQL_PORT:$PQL_PORT -e PQL_PORT=$PQL_PORT -e MAX_TASKQUEUE_ACTIVITIES_PER_SECOND=$MAX_TASKQUEUE_ACTIVITIES_PER_SECOND \
-e CONCURRENT_ACTIVITY_EXECUTION_SIZE=$CONCURRENT_ACTIVITY_EXECUTION_SIZE  \
-e CONCURRENT_WORKFLOW_EXECUTION_SIZE=$CONCURRENT_WORKFLOW_EXECUTION_SIZE  \
-e MAX_WORKFLOW_THREAD_COUNT=$MAX_WORKFLOW_THREAD_COUNT  \
-e DISABLE_EAGER_DISPATCH=DISABLE_EAGER_DISPATCH  \
-e CACHE_SIZE=$CACHE_SIZE  \
-e SLEEP_ACTIVITY_IN_MS=$SLEEP_ACTIVITY_IN_MS my-metric-worker-java

export PQL_PORT=8073
docker run -d -p $PQL_PORT:$PQL_PORT -e PQL_PORT=$PQL_PORT -e MAX_TASKQUEUE_ACTIVITIES_PER_SECOND=$MAX_TASKQUEUE_ACTIVITIES_PER_SECOND \
-e CONCURRENT_ACTIVITY_EXECUTION_SIZE=$CONCURRENT_ACTIVITY_EXECUTION_SIZE  \
-e CONCURRENT_WORKFLOW_EXECUTION_SIZE=$CONCURRENT_WORKFLOW_EXECUTION_SIZE  \
-e MAX_WORKFLOW_THREAD_COUNT=$MAX_WORKFLOW_THREAD_COUNT  \
-e DISABLE_EAGER_DISPATCH=DISABLE_EAGER_DISPATCH  \
-e CACHE_SIZE=$CACHE_SIZE  \
-e SLEEP_ACTIVITY_IN_MS=$SLEEP_ACTIVITY_IN_MS my-metric-worker-java

export PQL_PORT=8074
docker run -d -p $PQL_PORT:$PQL_PORT -e PQL_PORT=$PQL_PORT -e MAX_TASKQUEUE_ACTIVITIES_PER_SECOND=$MAX_TASKQUEUE_ACTIVITIES_PER_SECOND \
-e CONCURRENT_ACTIVITY_EXECUTION_SIZE=$CONCURRENT_ACTIVITY_EXECUTION_SIZE  \
-e CONCURRENT_WORKFLOW_EXECUTION_SIZE=$CONCURRENT_WORKFLOW_EXECUTION_SIZE  \
-e MAX_WORKFLOW_THREAD_COUNT=$MAX_WORKFLOW_THREAD_COUNT  \
-e DISABLE_EAGER_DISPATCH=DISABLE_EAGER_DISPATCH  \
-e CACHE_SIZE=$CACHE_SIZE  \
-e SLEEP_ACTIVITY_IN_MS=$SLEEP_ACTIVITY_IN_MS my-metric-worker-java

export PQL_PORT=8075
docker run -d -p $PQL_PORT:$PQL_PORT -e PQL_PORT=$PQL_PORT -e MAX_TASKQUEUE_ACTIVITIES_PER_SECOND=$MAX_TASKQUEUE_ACTIVITIES_PER_SECOND \
-e CONCURRENT_ACTIVITY_EXECUTION_SIZE=$CONCURRENT_ACTIVITY_EXECUTION_SIZE  \
-e CONCURRENT_WORKFLOW_EXECUTION_SIZE=$CONCURRENT_WORKFLOW_EXECUTION_SIZE  \
-e MAX_WORKFLOW_THREAD_COUNT=$MAX_WORKFLOW_THREAD_COUNT  \
-e DISABLE_EAGER_DISPATCH=DISABLE_EAGER_DISPATCH  \
-e CACHE_SIZE=$CACHE_SIZE  \
-e SLEEP_ACTIVITY_IN_MS=$SLEEP_ACTIVITY_IN_MS my-metric-worker-java

export PQL_PORT=8076
docker run -d -p $PQL_PORT:$PQL_PORT -e PQL_PORT=$PQL_PORT -e MAX_TASKQUEUE_ACTIVITIES_PER_SECOND=$MAX_TASKQUEUE_ACTIVITIES_PER_SECOND \
-e CONCURRENT_ACTIVITY_EXECUTION_SIZE=$CONCURRENT_ACTIVITY_EXECUTION_SIZE  \
-e CONCURRENT_WORKFLOW_EXECUTION_SIZE=$CONCURRENT_WORKFLOW_EXECUTION_SIZE  \
-e MAX_WORKFLOW_THREAD_COUNT=$MAX_WORKFLOW_THREAD_COUNT  \
-e DISABLE_EAGER_DISPATCH=DISABLE_EAGER_DISPATCH  \
-e CACHE_SIZE=$CACHE_SIZE  \
-e SLEEP_ACTIVITY_IN_MS=$SLEEP_ACTIVITY_IN_MS my-metric-worker-java

export PQL_PORT=8077
docker run -d -p $PQL_PORT:$PQL_PORT -e PQL_PORT=$PQL_PORT -e MAX_TASKQUEUE_ACTIVITIES_PER_SECOND=$MAX_TASKQUEUE_ACTIVITIES_PER_SECOND \
-e CONCURRENT_ACTIVITY_EXECUTION_SIZE=$CONCURRENT_ACTIVITY_EXECUTION_SIZE  \
-e CONCURRENT_WORKFLOW_EXECUTION_SIZE=$CONCURRENT_WORKFLOW_EXECUTION_SIZE  \
-e MAX_WORKFLOW_THREAD_COUNT=$MAX_WORKFLOW_THREAD_COUNT  \
-e DISABLE_EAGER_DISPATCH=DISABLE_EAGER_DISPATCH  \
-e CACHE_SIZE=$CACHE_SIZE  \
-e SLEEP_ACTIVITY_IN_MS=$SLEEP_ACTIVITY_IN_MS my-metric-worker-java

export PQL_PORT=8078
docker run -d -p $PQL_PORT:$PQL_PORT -e PQL_PORT=$PQL_PORT -e MAX_TASKQUEUE_ACTIVITIES_PER_SECOND=$MAX_TASKQUEUE_ACTIVITIES_PER_SECOND \
-e CONCURRENT_ACTIVITY_EXECUTION_SIZE=$CONCURRENT_ACTIVITY_EXECUTION_SIZE  \
-e CONCURRENT_WORKFLOW_EXECUTION_SIZE=$CONCURRENT_WORKFLOW_EXECUTION_SIZE  \
-e MAX_WORKFLOW_THREAD_COUNT=$MAX_WORKFLOW_THREAD_COUNT  \
-e DISABLE_EAGER_DISPATCH=DISABLE_EAGER_DISPATCH  \
-e CACHE_SIZE=$CACHE_SIZE  \
-e SLEEP_ACTIVITY_IN_MS=$SLEEP_ACTIVITY_IN_MS my-metric-worker-java

export PQL_PORT=8079
docker run -d -p $PQL_PORT:$PQL_PORT -e PQL_PORT=$PQL_PORT -e MAX_TASKQUEUE_ACTIVITIES_PER_SECOND=$MAX_TASKQUEUE_ACTIVITIES_PER_SECOND \
-e CONCURRENT_ACTIVITY_EXECUTION_SIZE=$CONCURRENT_ACTIVITY_EXECUTION_SIZE  \
-e CONCURRENT_WORKFLOW_EXECUTION_SIZE=$CONCURRENT_WORKFLOW_EXECUTION_SIZE  \
-e MAX_WORKFLOW_THREAD_COUNT=$MAX_WORKFLOW_THREAD_COUNT  \
-e DISABLE_EAGER_DISPATCH=DISABLE_EAGER_DISPATCH  \
-e CACHE_SIZE=$CACHE_SIZE  \
-e SLEEP_ACTIVITY_IN_MS=$SLEEP_ACTIVITY_IN_MS my-metric-worker-java
