receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317
#  prometheus:
#    config:
#      scrape_configs:
#        - job_name: 'otel-collector'
#          scrape_interval: 10s
#          static_configs:
#            - targets: ['java-worker:8071']
processors:
  batch:
    send_batch_max_size: 1000
    timeout: 30s
    send_batch_size : 800

  memory_limiter:
    check_interval: 1s
    limit_percentage: 70
    spike_limit_percentage: 30

exporters:
  debug:
    verbosity: detailed
  prometheusremotewrite:
    endpoint: "http://prometheus:9090/api/v1/write"

service:
  extensions: []
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [memory_limiter,batch]
      exporters: [prometheusremotewrite]