global:
  scrape_interval: 10s
scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets:
          - 'host.docker.internal:8010'
  - job_name: 'application'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'host.docker.internal:8080'
          - 'host.docker.internal:8081'
  - job_name: 'ts-sdk'
    static_configs:
      - targets:
          - 'host.docker.internal:9464'
  - job_name: 'client-java'
    static_configs:
      - targets:
          - 'host.docker.internal:8071'
          - 'host.docker.internal:8072'
          - 'host.docker.internal:8073'
          - 'host.docker.internal:8074'
          - 'host.docker.internal:8075'
          - 'host.docker.internal:8076'
          - 'host.docker.internal:8077'
          - 'host.docker.internal:8078'
          - 'host.docker.internal:8079'
  - job_name: 'client-java_worker'
    static_configs:
      - targets:
          - 'host.docker.internal:8061'
          - 'host.docker.internal:8062'
          - 'host.docker.internal:8063'
          - 'host.docker.internal:8064'
          - 'host.docker.internal:8065'
          - 'host.docker.internal:8066'
          - 'host.docker.internal:8067'
          - 'host.docker.internal:8068'
          - 'host.docker.internal:8069'
  - job_name: 'python_core_metrics'
    static_configs:
      - targets:
          - 'host.docker.internal:8085'
          - 'host.docker.internal:8086'
        labels:
          source: 'python_metric'
  - job_name: 'go_metrics'
    static_configs:
      - targets:
          - 'host.docker.internal:9095'
          - 'host.docker.internal:9096'
        labels:
          source: 'python_metric'

  - job_name: 'collector'
    static_configs:
      - targets:
          - 'host.docker.internal:8889'
        labels:
          source: 'collector_8889'

  - job_name: "cloud-metrics"
    scheme: https
    metrics_path: /v1/metrics
    static_configs:
      - targets:
          - 'metrics.temporal.io'
    authorization:
      type: Bearer
      credentials: ${CLOUD_METRICS_API_KEY}
