global:
  scrape_interval: 10s
scrape_configs:
  - job_name: 'application'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'host.docker.internal:8080'
          - 'host.docker.internal:8081'
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['host.docker.internal:8085']


