{
 "title": "Temporal Cloud External Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "temporal_namespace",
    "query": {
     "query": "label_values(temporal_namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "State Transitions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "State Transitions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(temporal_cloud_v0_state_transition_count{temporal_namespace=~\"$temporal_namespace\"}[$__rate_interval])) by (temporal_namespace)",
     "legendFormat": "{{temporal_namespace}}"
    }
   ]
  },
  {
   "title": "30 Day State Transitions",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(temporal_cloud_v0_state_transition_count{temporal_namespace=~\"$temporal_namespace\"}[30d])) by (temporal_namespace)",
     "legendFormat": "{{temporal_namespace}}"
    }
   ]
  },
  {
   "title": "7 Day State Transitions",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(temporal_cloud_v0_state_transition_count{temporal_namespace=~\"$temporal_namespace\"}[7d])) by (temporal_namespace)",
     "legendFormat": "{{temporal_namespace}}"
    }
   ]
  },
  {
   "title": "1 Day State Transitions",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(temporal_cloud_v0_state_transition_count{temporal_namespace=~\"$temporal_namespace\"}[1d])) by (temporal_namespace)",
     "legendFormat": "{{temporal_namespace}}"
    }
   ]
  },
  { "title": "Actions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Actions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(rate(temporal_cloud_v0_total_action_count{temporal_namespace=~\"$temporal_namespace\"}[$__rate_interval])) by (temporal_namespace)",
     "legendFormat": "{{temporal_namespace}}"
    }
   ]
  },
  {
   "title": "30 Days Actions",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(temporal_cloud_v0_total_action_count{temporal_namespace=~\"$temporal_namespace\"}[30d])) by (temporal_namespace)",
     "legendFormat": "{{temporal_namespace}}"
    }
   ]
  },
  {
   "title": "7 Days Actions",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(temporal_cloud_v0_total_action_count{temporal_namespace=~\"$temporal_namespace\"}[7d])) by (temporal_namespace)",
     "legendFormat": "{{temporal_namespace}}"
    }
   ]
  },
  {
   "title": "1 Day Actions",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(temporal_cloud_v0_total_action_count{temporal_namespace=~\"$temporal_namespace\"}[1d])) by (temporal_namespace)",
     "legendFormat": "{{temporal_namespace}}"
    }
   ]
  },
  {
   "title": "Workflows Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Workflow Success",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum(rate(temporal_cloud_v0_workflow_success_count{temporal_namespace=~\"$temporal_namespace\"}[$__rate_interval])) by (temporal_namespace)",
     "legendFormat": "{{temporal_namespace}}"
    }
   ]
  },
  {
   "title": "Workflow Timeouts",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "sum(rate(temporal_cloud_v0_workflow_timeout_count{temporal_namespace=~\"$temporal_namespace\"}[$__rate_interval])) by (temporal_namespace)",
     "legendFormat": "{{temporal_namespace}}"
    }
   ]
  },
  {
   "title": "Workflow Failed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum(rate(temporal_cloud_v0_workflow_failed_count{temporal_namespace=~\"$temporal_namespace\"}[$__rate_interval])) by (temporal_namespace)",
     "legendFormat": "{{temporal_namespace}}"
    }
   ]
  },
  {
   "title": "Workflow Continued as New",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "sum(rate(temporal_cloud_v0_workflow_continued_as_new_count{temporal_namespace=~\"$temporal_namespace\"}[$__rate_interval])) by (temporal_namespace)",
     "legendFormat": "{{temporal_namespace}}"
    }
   ]
  },
  {
   "title": "Temporal Service Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Frontend Service Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum(rate(temporal_cloud_v0_frontend_service_request_count{temporal_namespace=~\"$temporal_namespace\"}[$__rate_interval])) by (temporal_namespace,operation)",
     "legendFormat": "{{temporal_namespace}} - {{operation}}"
    }
   ]
  },
  {
   "title": "Frontend Service Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "sum(rate(temporal_cloud_v0_frontend_service_error_count{temporal_namespace=~\"$temporal_namespace\"}[$__rate_interval])) by (temporal_namespace,operation)",
     "legendFormat": "{{temporal_namespace}} - {{operation}}"
    }
   ]
  },
  { "title": "Temporal Service Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "StartWorkflowExecution Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(temporal_cloud_v0_service_latency_bucket{operation=\"StartWorkflowExecution\"}[$__rate_interval])) by (temporal_namespace, operation, le))",
     "legendFormat": "{{ temporal_namespace }}  - 50th Percentile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(temporal_cloud_v0_service_latency_bucket{operation=\"StartWorkflowExecution\"}[$__rate_interval])) by (temporal_namespace, operation, le))",
     "legendFormat": "{{ temporal_namespace }}  - 99th Percentile"
    }
   ]
  },
  {
   "title": "SignalWorkflowExecution Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(temporal_cloud_v0_service_latency_bucket{operation=\"SignalWorkflowExecution\"}[$__rate_interval])) by (temporal_namespace, operation, le))",
     "legendFormat": "{{ temporal_namespace }}  - 50th Percentile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(temporal_cloud_v0_service_latency_bucket{operation=\"SignalWorkflowExecution\"}[$__rate_interval])) by (temporal_namespace, operation, le))",
     "legendFormat": "{{ temporal_namespace }}  - 99th Percentile"
    }
   ]
  },
  {
   "title": "SignalWithStartWorkflowExecution Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(temporal_cloud_v0_service_latency_bucket{operation=\"SignalWithStartWorkflowExecution\"}[$__rate_interval])) by (temporal_namespace, operation, le))",
     "legendFormat": "{{ temporal_namespace }}  - 50th Percentile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(temporal_cloud_v0_service_latency_bucket{operation=\"SignalWithStartWorkflowExecution\"}[$__rate_interval])) by (temporal_namespace, operation, le))",
     "legendFormat": "{{ temporal_namespace }}  - 99th Percentile"
    }
   ]
  },
  {
   "title": "Workers and Tasks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Worker Poll Success",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "sum(rate(temporal_cloud_v0_poll_success_count{temporal_namespace=~\"$temporal_namespace\"}[$__rate_interval])) by (temporal_namespace)",
     "legendFormat": "{{temporal_namespace}}"
    }
   ]
  },
  {
   "title": "Worker Poll Timeout",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 61 },
   "targets": [
    {
     "expr": "sum(rate(temporal_cloud_v0_poll_timeout_count{temporal_namespace=~\"$temporal_namespace\"}[$__rate_interval])) by (temporal_namespace)",
     "legendFormat": "{{temporal_namespace}}"
    }
   ]
  },
  {
   "title": "Worker Poll Success Sync",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "sum(rate(temporal_cloud_v0_poll_success_sync_count{temporal_namespace=~\"$temporal_namespace\"}[$__rate_interval])) by (temporal_namespace)",
     "legendFormat": "{{temporal_namespace}}"
    }
   ]
  },
  {
   "title": "Worker Poll Success Async",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 70 },
   "targets": [
    {
     "expr": "sum(rate(temporal_cloud_v0_poll_success_count{temporal_namespace=~\"$temporal_namespace\"}[$__rate_interval])) by (temporal_namespace) - sum(rate(temporal_cloud_v0_poll_success_sync_count{temporal_namespace=~\"$temporal_namespace\"}[$__rate_interval])) by (temporal_namespace)",
     "legendFormat": "{{temporal_namespace}}"
    }
   ]
  }
 ]
}